public class ApiResponseWrapper1 {
    
    
   
    public String id { get; set; }
    public String name { get; set; }
    public DataWrapper data { get; set; }


public class DataWrapper {
    public String color { get; set; }
    public String capacity { get; set; }
    public String capacityGB { get; set; }
    public Decimal price { get; set; }
    public String generation { get; set; }
    public Integer year { get; set; }
    public String cpuModel { get; set; }
    public String hardDiskSize { get; set; }
    public String strapColour { get; set; }
    public String caseSize { get; set; }
    public String description { get; set; }
    public Decimal screenSize { get; set; }
}

    
    
    
    

}