public class createAnumberPattern {
    public static void num(){
             for (Integer i = 1; i <= 5; i++) {
            for (Integer j = 1; j <= i; j++) {
                System.debug(j);
            }
            System.debug(''); // Print a new line after each row
        }
    }
    
    
    
    
    
    
    }
    
    
    
    
    
    
    
    
      //  for(integer i=0; i==5;i++){
         // for(integer j=1;j<i;j++)
        //  {
         //     system.debug(j);
         // }
               
          
     // }
   // }
   

   
//